### ISSUE TITLE
Create release page

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/site#103]
## Description
Add a release page to hold download links for wallet, server, and miner binaries.

## Context
https://gitter.im/grin_community/dev?at=5c6c229ca7d733509d912c92:

> Gary Yu @garyyu Feb 19 17:37
> with multiple projects, I think we need a release page on our website, to hold 3 binaries for one release: server, wallet, miner?
> instead of on each github project.
> 
> Yeastplume @yeastplume Feb 19 17:37
> @garyyu sure, we can just link from there
> 
> Gary Yu @garyyu Feb 19 17:37

**Comment by lehnberg** [comment]
Would be great to have it in time for release of `v1.1.0` (ETA a couple of weeks).

**Comment by arteagabriel** [comment]
@lehnberg Does this still need to be done? I'd love to help out!

**Comment by garyyu** [comment]
@arteagabriel  Yes, still need :-)  thanks if you can help out 😄

**Comment by arteagabriel** [comment]
@garyyu ok cool! I'll see what I can do. I'm guessing if I have any questions to ask on gitter?

**Comment by garyyu** [comment]
Yes. 

And propose to use https://gitter.im/grin_community/design for `site` design related discussion.

**Comment by lehnberg** [comment]
Thanks for picking this up @arteagabriel! 🥇
 You can always ask questions here on the ticket as well.

**Comment by kargakis** [comment]
I guess the last thing missing from https://grin.mw/download is the miner binary?

**Comment by lehnberg** [comment]
Arguably it's good enough, not sure how useful grin-miner is beyond its role as a reference miner. Closing 👍
