### ISSUE TITLE
 Cannot read property 'donations' on FoG page

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/site#111]
On Chrome and Safari macOS. https://grin-tech.org/friends

```
Uncaught (in promise) TypeError: Cannot read property 'donations' of undefined
    at <anonymous>:48:19
    at Array.forEach (<anonymous>)
    at <anonymous>:44:17
```

Related to https://github.com/mimblewimble/site/pull/106

**Comment by lehnberg** [comment]
Just tried to reproduce in Chrome and Safari on macOS but failed, we've been fixing some other stuff, can you confirm it works now?

**Comment by lehnberg** [comment]
Cannot reproduce. Closing
