### ISSUE TITLE
secure grin-tech.org by ssl certs

### ISSUE THREAD

**Issue by zhizhongzhiwai** [mimblewimble/site#12]
there are donation bitcoin address on raise fund page, 
would you secure the site by ssl certs??

**Comment by lehnberg** [comment]
@zhizhongzhiwai https://grin-tech.org <- seems like it's already implemented, no?

**Comment by zhizhongzhiwai** [comment]
when input grin-tech.org to chrome address bar, the link is not secured by ssl.
if input https://grin-tech.org, the link is secured.

**Comment by lehnberg** [comment]
Yep, I can reproduce this on Firefox as well. Seems SSL is not defaulting.

**Comment by lehnberg** [comment]
looks like we should enforce HTTPS in our repo settings, see here: https://help.github.com/articles/securing-your-github-pages-site-with-https/

@ignopeverell could you action and close?
