### ISSUE TITLE
Create announcement/blog page

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/site#128]
Issue to track the creation of an announcement page. Whether it being kept on forum and linked to, or a new section on its own, it would still be great to have it.
Would be used for release and vulnerabilities/major news.

**Comment by 0xb100d** [comment]
Yes link to the announcements sub-forum is a good idea to have linked obvious on the homepage.

**Comment by kargakis** [comment]
Is this fixed now with https://grin.mw/blog/?

**Comment by quentinlesceller** [comment]
Yes closing. Thanks @kargakis
