### ISSUE TITLE
Do not display donation addresses directly on website

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/site#151]
### Proposal

* Remove BTC, GRIN, ETH, etc donation addresses from funding / friends
* Publish donation addresses in a repo on GitHub, such as `/grin-pm` in text files
* Link directly to text files from website, with instructions on how to make sure it's contained in the the correct repo.

### Rationale

Strikes a decent trade-off between being easy to verify (i.e. quickly seeing something is off, without the need of PGP), and fairly hard to attack. Training the community to never expect a valid donation address directly on the website makes it harder to redirect to incorrect addresses.

### Context
> joltz 3:49 AM - Thu
> Unrelated- with the domain chaos would it make sense to pgp sign donation addresses for the site?
> 
> lehnberg 2:35 PM
> how exactly? just PRing in a commit that confirms the donation address? or something more elaborate?
> 
> joltz 6:01 PM
> a signed commit is good but it doesn't make any guarantees for users seeing the content served from a website. the website owner could serve any content they want (a mirror of github website with different donation addresses). if the addresses were shown on the site with a pgp signature and if users actually verified the signatures it would mitigate that kind of attack. edit: this is only mitigated if the community understands to expect pgp signatures with donation addresses, otherwise attacker could just not serve pgp info
> though i guess users can check the github to verify it matches on the website. i'm not sure what a user would be more likely to do- manually verify by eye that an address matches on github, or manually verify a pgp signature (and import the key if they haven't already)
> 
> lehnberg 7:14 PM
> yeah - it's a good question. an alternative could be to not display addresses on the website at all, and instead link to a file in a repo somewhere that lists the addresses?
> not sure if that helps though, but I suppose it's harder to spoof github and the repo?
> 
> joltz 7:15 PM
> i like that compromise 👍
> and make it clear that whatever repo it is in is the only source for donation addresses, always get them from that file etc.
> 
> lehnberg 7:16 PM
> yeah. also makes version control clear etc. will create an issue

**Comment by nijynot** [comment]
Agreed, have been copy pasting the donation addresses back and forth (and double checking it's correct). Makes a lot of sense to put it in a github repo instead.
