### ISSUE TITLE
Replace fonts on the Google tracker (fonts.gstatic.com) with alternative, more ethical, non-tracking tools

### ISSUE THREAD

**Issue by cis-cat** [mimblewimble/site#191]
**Description the bug**
Currently, site https://grin.mw uses `fonts.gstatic.org`, which is considered a tracker.
Using the resource *google.com is unethical with the GRIN community.

**Proposed solution**
Use fonts from local repository.
or
This can also be solved using system fonts alike https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L29

**Comment by lehnberg** [comment]
Ping @nijynot

**Comment by nijynot** [comment]
@cis-cat Good point, will download the Space Mono font and serve it statically from the repo instead.
