### ISSUE TITLE
Keybase widget down

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/site#192]
Looks like the service is down. @nijynot could you investigate? :)

![Screenshot-2020-05-20-at-12-09-54](https://i.ibb.co/gVfSs31/Screenshot-2020-05-20-at-12-09-54.png)

**Comment by nijynot** [comment]
Good catch, should be fixed now! :+1:
Was a problem with the Let's Encrypto auto renewal.

**Comment by lehnberg** [comment]
Yes, up and running again, nice job turning around so quickly! 🚀
