### ISSUE TITLE
Transparent website header does not look great when mixed with main body

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/site#231]
I like the simplicity of the header and the website in general but we may want to consider using a non-transparent header to avoid mixing header letters with body letters which is not a great UX. I can submit a PR if folks are happy with the change. If this has been discussed in the past and the consensus was to keep it as is feel free to close this issue.
![Screenshot from 2020-09-30 19-00-16](https://user-images.githubusercontent.com/3900799/94716730-914d6400-034f-11eb-9294-e937c666b4dc.png)

**Comment by lehnberg** [comment]
It's a conscious design decision, very much in vogue these days I believe.
