### ISSUE TITLE
GRIN General fund page outdated

### ISSUE THREAD

**Issue by l33d4n** [mimblewimble/site#245]
![image](https://user-images.githubusercontent.com/8020386/109156689-1b3d1400-77ac-11eb-921f-c8a005636f85.png)

The [general fund page](https://grin.mw/fund) has not been updated for over 7 months.

Also, the transparency reports for **2020Q3** and **2020Q4** have never been published
https://github.com/mimblewimble/grin-pm/tree/master/financials/reports

**Comment by quentinlesceller** [comment]
Closing. See #248.
