### ISSUE TITLE
feat: have a page that tracks all past campaigns

### ISSUE THREAD

**Issue by sesam** [mimblewimble/site#46]
and link to it at the end of Current and Recent Campaigns

also

> General Funding for Grin’s Development, currently fully directed toward the security audit.
> Status: Always Open - 0.0 BTC donated to date

looks wrong or probably superfluous, since just below the total amount of the security campaign is listed

thank you @kargakis

**Comment by kargakis** [comment]
Fixed by https://github.com/mimblewimble/site/pull/38

**Comment by kargakis** [comment]
@ignopeverell you can close this issue
