### ISSUE TITLE
update logo to better ratio version

### ISSUE THREAD

**Issue by 0xb100d** [mimblewimble/site#53]
Miso/nijinot on the forum improved the ratios of the logo slightly:
https://www.grin-forum.org/t/grin-logos-for-community-consideration/155/214

direct link to svg
https://gist.github.com/nijynot/5fc37675abbd53171a41a9f22ae1c710

**Comment by lehnberg** [comment]
I wouldn't say there's a consensus around this at the moment, see for example here: 
https://www.grin-forum.org/t/grin-logos-for-community-consideration/155/218

If such a change should occur, might be worth to discuss further.

**Comment by ignopeverell** [comment]
Indeed, I still prefer the original.

**Comment by sesam** [comment]
The old/current looks more human, while the new looks a bit too much like an emoticon, so there might be some advantage to keep it more human and less symmetrical vs this new adjusted one.

**Comment by 0xb100d** [comment]
If it ain’t broke!
