### ISSUE TITLE
Certificates expired

### ISSUE THREAD

**Issue by erikzrekz** [mimblewimble/site#55]
https://download.wpsoftware.net/bitcoin/wizardry/mimblewimble.pdf
<img width="1552" alt="screen shot 2019-01-04 at 9 24 27 am" src="https://user-images.githubusercontent.com/3126690/50692689-b68a3280-1002-11e9-9634-33e7976c0cda.png">

https://download.wpsoftware.net/bitcoin/wizardry/mimblewimble.txt
<img width="1552" alt="screen shot 2019-01-04 at 9 24 21 am" src="https://user-images.githubusercontent.com/3126690/50692690-b68a3280-1002-11e9-92d3-c31efd77c028.png">

**Comment by lehnberg** [comment]
This is not a site under Grin's control. I believe it's @apoelstra's. Closing.

**Comment by apoelstra** [comment]
Sorry about this.

FYI I can be contacted at apoelstra at blockstream.com if this happens in future and I'll respond within a couple hours.
